# Practice Notebook (Session 3)
**Linear Algebra Applications — problems with answers**

Generated: 2025-09-05T16:20:19.797852 UTC

---

## Problem 1 — Linear Regression (Normal Equation)
Given the design matrix X and targets Y (6 samples, 2 features + bias), compute coefficients using normal equation:

$$\beta = (X^T X)^{-1} X^T Y$$

In [1]:
import numpy as np
X = np.array([[1, 1.2, 2],
              [1, 1.5, 2],
              [1, 2.25, 3],
              [1, 2.5, 3],
              [1, 2.5, 2],
              [1, 1.5, 3]])
Y = np.array([40, 55, 75, 85, 80, 70])
beta = np.linalg.inv(X.T @ X) @ (X.T @ Y)
print('Estimated coefficients (β0, β1, β2):', beta)

Estimated coefficients (β0, β1, β2): [-2.43662505 23.32576617 10.16931517]


**Answer (computed):** `[-2.436625047294541, 23.325766174801362, 10.169315172152784]`

## Problem 2 — Image Basics
(a) Represent a 4×4 grayscale image as a NumPy array. (b) Create a 2×2 RGB image (explicit pixel values).

In [2]:
import numpy as np
np.random.seed(1)
gray4 = np.random.randint(0,256,(4,4))
print('4x4 grayscale matrix:\n', gray4)

rgb2 = np.zeros((2,2,3), dtype=int)
rgb2[0,0] = [255,0,0]
rgb2[0,1] = [0,255,0]
rgb2[1,0] = [0,0,255]
rgb2[1,1] = [255,255,0]
print('\n2x2 RGB image array:\n', rgb2)

4x4 grayscale matrix:
 [[ 37 235 140  72]
 [255 137 203 133]
 [ 79 192 144 129]
 [204  71 237 252]]

2x2 RGB image array:
 [[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255   0]]]


**Answer:** sample grayscale and RGB arrays are shown in the code output above.

## Problem 3 — Linear Transformations
Rotate point (1,0) by 45° using homogeneous coordinates and a rotation matrix.

In [3]:
import numpy as np
theta = np.pi/4
R45 = np.array([[np.cos(theta), -np.sin(theta), 0],
                [np.sin(theta),  np.cos(theta), 0],
                [0, 0, 1]])
v = np.array([1,0,1])
rotated = R45 @ v
print('Rotated point (homogeneous):', rotated)
print('2D coordinates:', rotated[:2])

Rotated point (homogeneous): [0.70710678 0.70710678 1.        ]
2D coordinates: [0.70710678 0.70710678]


**Answer (computed):** rotated 2D point ≈ `[0.7071067811865477, 0.7071067811865476]`

## Problem 4 — Filtering (Convolution)
Apply a 3×3 sharpening kernel to the sample 5×5 grayscale image. Show the filtered output.

In [4]:
import numpy as np
sample_img = np.arange(25).reshape(5,5).astype(float)
kernel_sharp = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
# simple 'same' convolution
from scipy.signal import convolve2d
filtered = convolve2d(sample_img, kernel_sharp, mode='same', boundary='symm')
print('Sample image:\n', sample_img)
print('\nFiltered image:\n', filtered)

Sample image:
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]

Filtered image:
 [[-6. -4. -3. -2.  0.]
 [ 4.  6.  7.  8. 10.]
 [ 9. 11. 12. 13. 15.]
 [14. 16. 17. 18. 20.]
 [24. 26. 27. 28. 30.]]


**Answer:** filtered image printed above (see code output).

## Problem 5 — Applications (Data augmentation simple example)
Rotate point (1,2) by angles 15°, 30°, 45° and show results.

In [5]:
import numpy as np
angles = [15,30,45]
results = []
for a in angles:
    th = np.deg2rad(a)
    R = np.array([[np.cos(th), -np.sin(th)],[np.sin(th), np.cos(th)]])
    results.append((a, (R @ np.array([1,2])).tolist()))
print('Rotated points:', results)

Rotated points: [(15, [0.44828773608402683, 2.190670697680657]), (30, [-0.13397459621556118, 2.232050807568877]), (45, [-0.7071067811865476, 2.121320343559643])]


**Answer (computed):** [(15, array([0.44828774, 2.1906707 ])), (30, array([-0.1339746 ,  2.23205081])), (45, array([-0.70710678,  2.12132034]))]