# Practice Notebook — Session 4 (PCA & SVD)
Problems with answers for PCA, Covariance, SVD, and Image Compression.

Generated: 2025-09-05T16:24:07.606850 UTC

---

## Problem 1 — Covariance Matrix & Eigen decomposition
Given data matrix (6 samples, 2 features):

```
X = [[12,7],[10,4],[2,3],[8,5],[3,3],[1,2]]
```
Compute the mean-centered covariance matrix and its eigenvalues/eigenvectors.

In [1]:
import numpy as np
X = np.array([[12,7],[10,4],[2,3],[8,5],[3,3],[1,2]], dtype=float)
Xc = X - X.mean(axis=0)
C = np.cov(Xc.T)
vals, vecs = np.linalg.eig(C)
print('Covariance matrix:\n', C)
print('\nEigenvalues:', vals)
print('Eigenvectors:\n', vecs)

Covariance matrix:
 [[21.2  7.4]
 [ 7.4  3.2]]

Eigenvalues: [23.85160933  0.54839067]
Eigenvectors:
 [[ 0.94138873 -0.33732367]
 [ 0.33732367  0.94138873]]


**Answer (computed):** eigenvalues = `[23.85160933090361, 0.5483906690963938]`, eigenvectors =
```
[[ 0.94138873 -0.33732367]
 [ 0.33732367  0.94138873]]
```

## Problem 2 — PCA projection
Project the standardized data onto the first principal component (PC1) and show projected coordinates.

In [2]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
X = np.array([[12,7],[10,4],[2,3],[8,5],[3,3],[1,2]], dtype=float)
Xs = (X - X.mean(axis=0)) / X.std(axis=0)
pca = PCA(n_components=1)
proj = pca.fit_transform(Xs)
print('Projected coordinates onto PC1:\n', proj.flatten())
print('Explained variance ratio:', pca.explained_variance_ratio_)

Projected coordinates onto PC1:
 [ 2.30842798  0.67292658 -1.10593929  0.76947599 -0.93770764 -1.70718363]
Explained variance ratio: [0.94921971]


**Answer:** projection shown in code output; PC1 direction is the first principal component computed by PCA.

## Problem 3 — Singular Value Decomposition (SVD)
Compute SVD for matrix:

```
A = [[3,1],[1,3]]
```
Show U, Σ, V^T and verify A = U Σ V^T.

In [3]:
import numpy as np
A = np.array([[3,1],[1,3]], dtype=float)
U, S, Vt = np.linalg.svd(A)
Sigma = np.zeros_like(A)
np.fill_diagonal(Sigma, S)
print('U:\n', U)
print('\nSingular values:', S)
print('\nV^T:\n', Vt)
print('\nReconstructed A:\n', U @ Sigma @ Vt)

U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Singular values: [4. 2.]

V^T:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Reconstructed A:
 [[3. 1.]
 [1. 3.]]


**Answer:** singular values and matrices printed above; reconstruction should match A.

## Problem 4 — Image Compression using SVD
Given small grayscale image:
```
img = [[100,120,130],[90,110,115],[80,95,105]]
```
Compute rank-1 approximation (k=1) using SVD and show compressed image matrix.

In [4]:
import numpy as np
img = np.array([[100,120,130],[90,110,115],[80,95,105]], dtype=float)
U, S, Vt = np.linalg.svd(img, full_matrices=False)
k = 1
img_k = U[:, :k] @ np.diag(S[:k]) @ Vt[:k, :]
print('Rank-1 approx (k=1):\n', np.round(img_k, 3))
print('\nOriginal image:\n', img)

Rank-1 approx (k=1):
 [[100.009 120.419 129.604]
 [ 89.964 108.323 116.586]
 [ 80.029  96.362 103.712]]

Original image:
 [[100. 120. 130.]
 [ 90. 110. 115.]
 [ 80.  95. 105.]]


**Answer:** rank-1 approximation printed above; compare visually to original.

---
Notebook generated on 2025-09-05T16:24:07.613221 UTC
