# Rough Notebook — Session 4 (PCA & SVD)
Run code hints and experiments for PCA and SVD.

---

## Imports and helper notes

In [1]:
import numpy as np
from numpy.linalg import svd, eig
print('Loaded numpy and linalg svd/eig')

Loaded numpy and linalg svd/eig


## Covariance and eigen decomposition example

In [2]:
X = np.array([[12,7],[10,4],[2,3],[8,5],[3,3],[1,2]], dtype=float)
Xc = X - X.mean(axis=0)
C = np.cov(Xc.T)
print('Covariance:\n', C)
print('\nEigenvals/eigvecs:\n', np.linalg.eig(C))

Covariance:
 [[21.2  7.4]
 [ 7.4  3.2]]

Eigenvals/eigvecs:
 EigResult(eigenvalues=array([23.85160933,  0.54839067]), eigenvectors=array([[ 0.94138873, -0.33732367],
       [ 0.33732367,  0.94138873]]))


## PCA with sklearn hint

In [3]:
from sklearn.decomposition import PCA
X = np.array([[12,7],[10,4],[2,3],[8,5],[3,3],[1,2]], dtype=float)
X_scaled = (X - X.mean(axis=0)) / X.std(axis=0)
pca = PCA()
print('PCA components:\n', pca.fit(X_scaled).components_)
print('Explained variance ratio:', pca.explained_variance_ratio_)

PCA components:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
Explained variance ratio: [0.94921971 0.05078029]


## SVD demonstration

In [4]:
A = np.array([[3,1],[1,3]], dtype=float)
U,S,Vt = svd(A)
print('U:\n', U)
print('\nS:\n', S)
print('\nVt:\n', Vt)
print('\nReconstruct A:\n', U @ np.diag(S) @ Vt)

U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

S:
 [4. 2.]

Vt:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Reconstruct A:
 [[3. 1.]
 [1. 3.]]


## Image compression quick demo

In [5]:
img = np.array([[100,120,130],[90,110,115],[80,95,105]], dtype=float)
U,S,Vt = svd(img, full_matrices=False)
for k in [1,2,3]:
    img_k = U[:,:k] @ np.diag(S[:k]) @ Vt[:k,:]
    print(f'k={k} approx:\n', np.round(img_k,3))

k=1 approx:
 [[100.009 120.419 129.604]
 [ 89.964 108.323 116.586]
 [ 80.029  96.362 103.712]]
k=2 approx:
 [[100. 120. 130.]
 [ 90. 110. 115.]
 [ 80.  95. 105.]]
k=3 approx:
 [[100. 120. 130.]
 [ 90. 110. 115.]
 [ 80.  95. 105.]]
