In [1]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, 3, 4],
              [3, 5, 5],
              [5, 6, 3]])

# Result vector B
B = np.array([11, 15, 19])

# Solve AX = B
X = np.linalg.solve(A, B)
print("Solution for [a, b, c]:", X)

Solution for [a, b, c]: [ 3.5 -0.4  1.3]


In [2]:
# Example: Linear transformation
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])   # Feature matrix

W = np.array([[2],
              [1]])      # Weights

b = 1                   # Bias

# Compute prediction Y = XW + b
Y = X @ W + b
print("Predictions:\n", Y)

# Example: Image as matrix
image = np.random.randint(0, 256, (4, 4))  # 4x4 grayscale image
print("Image matrix:\n", image)

Predictions:
 [[ 5]
 [11]
 [17]]
Image matrix:
 [[187 200 153  24]
 [158  75  68 231]
 [232  39  17 226]
 [142 192 185  60]]


In [3]:
u = np.array([2, 3])
v = np.array([1, 4])

# Addition
print("u + v =", u + v)

# Subtraction
print("u - v =", u - v)

# Scalar multiplication
print("2 * u =", 2 * u)

# Dot product
print("Dot product:", np.dot(u, v))

# Norms
print("L1 norm of u:", np.linalg.norm(u, ord=1))
print("L2 norm of u:", np.linalg.norm(u))

u + v = [3 7]
u - v = [ 1 -1]
2 * u = [4 6]
Dot product: 14
L1 norm of u: 5.0
L2 norm of u: 3.605551275463989


In [4]:
# Example vectors as rows of matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

if np.isclose(det_A, 0):
    print("Vectors are linearly dependent")
else:
    print("Vectors are linearly independent")

Determinant of A: 0.0
Vectors are linearly dependent
