# Session 2 — Practice Notebook
**Linear Transformations & Matrices**

This notebook contains short problems (from the Session 2 READMEs). Each problem is followed by a code cell (reproducible) and an **Answer** cell that shows the computed result.

---


## Problem 1
Represent and solve the system in matrix form:

$$\begin{cases} x + y + z = 6 \\ 2y + 5z = -4 \\ 2x + 5y - z = 27 \end{cases}$$

Solve for $(x,y,z)$.

In [1]:
# Problem 1 — solve system
import numpy as np
A = np.array([[1,1,1],[0,2,5],[2,5,-1]], dtype=float)
b = np.array([6, -4, 27], dtype=float)
sol = np.linalg.solve(A, b)
print('Solution [x, y, z] =', sol)

Solution [x, y, z] = [ 5.  3. -2.]


**Answer (computed):** `[5.0, 3.0, -2.0]`

## Problem 2
Create a 4×4 random matrix using NumPy and compute its transpose. Show shapes as well.

In [2]:
# Problem 2 — 4x4 random matrix and transpose
import numpy as np
np.random.seed(0)
A = np.random.rand(4,4)
print('A:\n', A)
print('\nA.T:\n', A.T)
print('\nShapes:', A.shape, A.T.shape)

A:
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]

A.T:
 [[0.5488135  0.4236548  0.96366276 0.56804456]
 [0.71518937 0.64589411 0.38344152 0.92559664]
 [0.60276338 0.43758721 0.79172504 0.07103606]
 [0.54488318 0.891773   0.52889492 0.0871293 ]]

Shapes: (4, 4) (4, 4)


**Answer (sample matrix and its transpose shown in the code cell above).**

## Problem 3
Given vectors:

```
v1 = [2,3,1]
v2 = [4,6,2]
v3 = [1,0,1]
```

Check if they are linearly independent (use determinant and rank).

In [3]:
# Problem 3 — determinant and rank
import numpy as np
v1 = np.array([2,3,1])
v2 = np.array([4,6,2])
v3 = np.array([1,0,1])
M = np.vstack([v1, v2, v3])
print('Matrix M (rows = vectors):\n', M)
print('\ndet(M)=', np.linalg.det(M))
print('rank(M)=', np.linalg.matrix_rank(M))

Matrix M (rows = vectors):
 [[2 3 1]
 [4 6 2]
 [1 0 1]]

det(M)= 0.0
rank(M)= 2


**Answer (computed):** determinant = `0.0`, rank = `2` — therefore the vectors are linearly dependent.

## Problem 4
Create a random 3×3 matrix and check if it is orthogonal by verifying $A^T A = I$. (Show result of the check.)

In [4]:
# Problem 4 — orthogonality check
import numpy as np
A = np.random.rand(3,3)
ATA = A.T @ A
print('A:\n', A)
print('\nA^T A:\n', ATA)
print('\nIs A orthogonal? ->', np.allclose(ATA, np.eye(3)))

A:
 [[0.0202184  0.83261985 0.77815675]
 [0.87001215 0.97861834 0.79915856]
 [0.46147936 0.78052918 0.11827443]]

A^T A:
 [[0.97029312 1.22844219 0.76559195]
 [1.22844219 2.26017546 1.52229662]
 [0.76559195 1.52229662 1.25817118]]

Is A orthogonal? -> False


**Answer (computed sample):** `np.allclose(A^T A, I)` = `False`

## Problem 5
Apply Gram–Schmidt to orthonormalize columns of the matrix:

```
G = [[2,2,4],[0,3,5],[0,4,5]]
```
Verify that Q^T Q ≈ I.

In [5]:
# Problem 5 — Gram-Schmidt
import numpy as np
G = np.array([[2.0,2.0,4.0],[0.0,3.0,5.0],[0.0,4.0,5.0]])
# Gram-Schmidt function

def gram_schmidt_cols(A):
    A = A.astype(float)
    m, n = A.shape
    Q = np.zeros((m, n))
    for j in range(n):
        v = A[:, j].copy()
        for i in range(j):
            proj = np.dot(Q[:, i], A[:, j]) * Q[:, i]
            v = v - proj
        norm = np.linalg.norm(v)
        if norm < 1e-12:
            Q[:, j] = v
        else:
            Q[:, j] = v / norm
    return Q

Q = gram_schmidt_cols(G)
print('Q:\n', Q)
print('\nQ^T Q:\n', np.round(Q.T @ Q, 6))
print('\nIs Q orthonormal? ->', np.allclose(Q.T @ Q, np.eye(Q.shape[1])))

Q:
 [[ 1.   0.   0. ]
 [ 0.   0.6  0.8]
 [ 0.   0.8 -0.6]]

Q^T Q:
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]

Is Q orthonormal? -> True


**Answer (computed):** Q^T Q ≈
```
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]
```
Is orthonormal? `True`

## Problem 6
Compute eigenvalues and eigenvectors for A = [[2,1],[1,1]] and verify A v = λ v for one eigenpair.

In [6]:
# Problem 6 — eigenvalues/eigenvectors
import numpy as np
A = np.array([[2,1],[1,1]], dtype=float)
eigvals, eigvecs = np.linalg.eig(A)
print('eigvals=', eigvals)
print('eigvecs=\n', eigvecs)
# verify for first eigenpair
v = eigvecs[:,0]
l = eigvals[0]
print('\nA v =', A @ v)
print('l v =', l * v)
print('\nResidual (A v - l v) =', A @ v - l * v)

eigvals= [2.61803399 0.38196601]
eigvecs=
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]

A v = [2.22703273 1.37638192]
l v = [2.22703273 1.37638192]

Residual (A v - l v) = [0.00000000e+00 2.22044605e-16]


**Answer (computed):** eigenvalues = `[2.618033988749895, 0.3819660112501052]`, eigenvectors =
```
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
```
Residual for first eigenpair ≈ `[0.00000000e+00 2.22044605e-16]`

## Problem 7
Diagonalize A and compute A^5 using diagonalization (reuse A from Problem 6).

In [7]:
# Problem 7 — diagonalization and A^5
import numpy as np
A = np.array([[2,1],[1,1]], dtype=float)
vals, vecs = np.linalg.eig(A)
D5 = np.diag(vals**5)
A5 = vecs @ D5 @ np.linalg.inv(vecs)
print('A^5 =\n', np.round(A5,6))

A^5 =
 [[89. 55.]
 [55. 34.]]


**Answer (computed A^5):**
```
[[89. 55.]
 [55. 34.]]
```

## Problem 8
Construct a 2D rotation matrix for 90° and show why floating point gives tiny nonzero values for cos(π/2).

In [8]:
# Problem 8 — rotation matrix 90 degrees
import numpy as np
theta = np.pi/2
R = np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta), np.cos(theta)]])
print('R =\n', R)
print('\nRounded R =\n', np.round(R,6))

R =
 [[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]

Rounded R =
 [[ 0. -1.]
 [ 1.  0.]]


**Answer (computed):** Floating point leads to tiny nonzero values; rounding gives the exact integer-looking matrix for 90° rotation.