1. Apply a scaling transform with $s_x = 3, s_y = 0.5$ to vector $(2,4)$.  

In [2]:
import numpy as np

sx = 3
sy = 0.5

v = np.array([2, 4])

# scaling matrix
S = np.array([[sx, 0], [0, sy]])

print("Original vector:", v)
print("Scaling matrix:", S, sep="\n")

print("Scaling:", S @ v)

Original vector: [2 4]
Scaling matrix:
[[3.  0. ]
 [0.  0.5]]
Scaling: [6. 2.]


2. Reflect vector $(1,2)$ about the y-axis.  

In [3]:
# reflection matrix about y-axis
R = np.array([[-1, 0], [0, 1]])
print("Reflection matrix about y-axis:", R, sep="\n")
print("Reflection:", R @ v)

Reflection matrix about y-axis:
[[-1  0]
 [ 0  1]]
Reflection: [-2  4]


3. Project $(5,7)$ onto the x-axis.  

In [4]:
# projection matrix onto x-axis
P = np.array([[1, 0], [0, 0]])
print("Projection matrix onto x-axis:", P, sep="\n")
print("Projection:", P @ v)

Projection matrix onto x-axis:
[[1 0]
 [0 0]]
Projection: [2 0]


4. Rotate $(1,0)$ by $90^\circ$ and verify the result.  

In [5]:
# rotation matrix by 90 degrees
theta = np.pi / 2  # 90 degrees in radians
cos_theta, sin_theta = round(np.cos(theta), 2), round(np.sin(theta), 2)  # np.cos(theta), np.sin(theta)
R = np.array([[cos_theta, -sin_theta], [sin_theta, cos_theta]])
print("Rotation matrix by 90 degrees:", R, sep="\n")
print("Rotation:", R @ np.array([1, 0]))

Rotation matrix by 90 degrees:
[[ 0. -1.]
 [ 1.  0.]]
Rotation: [0. 1.]


1. Compute the determinant of:  

   $$
   \begin{bmatrix}
   1 & 2 \\
   3 & 4
   \end{bmatrix}
   $$  

In [6]:
A = np.array([[1, 2], [3, 4]])

det_A = np.linalg.det(A)
print("Matrix A:", A, sep="\n")
print("Determinant of A:", round(det_A, 2), sep="\n")

Matrix A:
[[1 2]
 [3 4]]
Determinant of A:
-2.0


2. Find the determinant of:  

   $$
   \begin{bmatrix}
   2 & 0 & 1 \\
   -1 & 3 & 2 \\
   3 & 1 & 0
   \end{bmatrix}
   $$  

In [7]:
A = np.array([[2, 0, 1],
              [3, 0, 0],
              [0, 0, 1]])

det_A = np.linalg.det(A)
print("Matrix A:", A, sep="\n")
print("Determinant of A:", round(det_A, 2), sep="\n")

Matrix A:
[[2 0 1]
 [3 0 0]
 [0 0 1]]
Determinant of A:
0.0


3. In Python, generate a random $4 \times 4$ matrix and compute its determinant using `np.linalg.det`.  

In [8]:
random_matrix = np.random.rand(4, 4)
det_random = np.linalg.det(random_matrix)
print("Random 4x4 matrix:", random_matrix, sep="\n")
print("Determinant of random matrix:", round(det_random, 2), sep="\n")

Random 4x4 matrix:
[[0.8861309  0.67722547 0.51832738 0.74393831]
 [0.73177231 0.42558369 0.76125291 0.48449504]
 [0.26881926 0.20529274 0.40022768 0.56223838]
 [0.76910561 0.1883271  0.12463752 0.44512771]]
Determinant of random matrix:
-0.06


1. Compute the inverse of  

   $$
   \begin{bmatrix}
   4 & 7 \\
   2 & 6
   \end{bmatrix}
   $$  

   Verify that $AA^{-1} = I$.  

In [9]:
A = np.array([[4, 7],
              [2, 6]])

A_inv = np.linalg.inv(A)
print("Matrix A:", A, sep="\n")

# Verify A * A_inv = I
identity = A @ A_inv
print("A * A_inv:", identity, sep="\n")

Matrix A:
[[4 7]
 [2 6]]
A * A_inv:
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


2. In Python, generate a random $3 \times 3$ matrix (with non-zero determinant) and compute its inverse.  

In [10]:
random_matrix = np.random.rand(3, 3)
random_matrix_inv = np.linalg.inv(random_matrix)
print("Random 3x3 matrix:", random_matrix, sep="\n")
print("Inverse of random matrix:", random_matrix_inv, sep="\n")

Random 3x3 matrix:
[[0.15003043 0.17170553 0.35445712]
 [0.09084415 0.50104315 0.97634152]
 [0.84231878 0.06637506 0.02982013]]
Inverse of random matrix:
[[  3.51294246  -1.29678155   0.70134582]
 [-57.74749     20.71910356   8.05119325]
 [ 29.30824236  -9.48782743  -4.19700309]]


3. Verify $(AB)^{-1} = B^{-1}A^{-1}$ using two random invertible matrices.

In [11]:
A = np.array([[4, 7],
              [2, 6]])

B = np.array([[1, 0],
              [0, 1]])

# verify (AB)^-1 = B^-1 A^-1
AB = A @ B
AB_inv = np.linalg.inv(AB)
B_inv = np.linalg.inv(B)
A_inv = np.linalg.inv(A)

B_inv_A_inv = B_inv @ A_inv
print("B^-1 A^-1:", B_inv_A_inv, sep="\n")
print("AB^-1:", AB_inv, sep="\n")
print("B^-1 A^-1 == AB^-1:", B_inv_A_inv == AB_inv)

B^-1 A^-1:
[[ 0.6 -0.7]
 [-0.2  0.4]]
AB^-1:
[[ 0.6 -0.7]
 [-0.2  0.4]]
B^-1 A^-1 == AB^-1: [[ True  True]
 [ True  True]]


1. Compute the determinant of a $4 \times 4$ diagonal matrix with diagonal entries $(1,2,3,4)$.  

In [12]:
A = np.array([[1, 0 , 0, 0],
                [0, 2, 0, 0],
                [0, 0, 3, 0],
                [0, 0, 0, 4]])
print("Determinant (Diagonal):", np.linalg.det(A))


Determinant (Diagonal): 23.999999999999993


2. Verify in Python that for an orthogonal matrix $Q$, $Q^T = Q^{-1}$.  

In [13]:
# Orthogonal matrix example (rotation 90°)
Q = np.array([[0, -1],
              [1,  0]])
print("Matrix Q (Orthogonal):", Q, sep="\n")

# verify for orthogonal matrix Q, Q^T = Q^-1
Q_T = Q.T
Q_inv = np.linalg.inv(Q)
print("Q^T:", Q_T, sep="\n")
print("Q^-1:", Q_inv, sep="\n")
print("Q^T == Q^-1 ?", np.allclose(Q_T, Q_inv))

Matrix Q (Orthogonal):
[[ 0 -1]
 [ 1  0]]
Q^T:
[[ 0  1]
 [-1  0]]
Q^-1:
[[ 0.  1.]
 [-1. -0.]]
Q^T == Q^-1 ? True


3. Take a $3 \times 3$ upper triangular matrix and check if its determinant equals the product of diagonal entries. 

In [14]:
triangular_matrix = np.array([[2, 3, 1],
                              [0, 5, 4],
                              [0, 0, 6]])
print("Upper Triangular Matrix:", triangular_matrix, sep="\n")

# checking if determinant equals product of diagonal entries
det_triangular = np.linalg.det(triangular_matrix)
prod_diagonal = np.prod(np.diag(triangular_matrix))

det_triangular == prod_diagonal

Upper Triangular Matrix:
[[2 3 1]
 [0 5 4]
 [0 0 6]]


np.False_

1. Verify that for the $2 \times 2$ rotation matrix  

   $$
   R = \begin{bmatrix}
   \cos\theta & -\sin\theta \\
   \sin\theta & \cos\theta
   \end{bmatrix}
   $$  

   we have $R^T R = I$.  

In [15]:
R = np.array([[np.cos(np.pi/4), -np.sin(np.pi/4)],
              [np.sin(np.pi/4),  np.cos(np.pi/4)]])
print("Rotation matrix by 45 degrees:", R, sep="\n")

R_T = R.T

# verify R_t @ R = I
identity = R_T @ R
print("R^T @ R:", identity, sep="\n")

Rotation matrix by 45 degrees:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
R^T @ R:
[[ 1.00000000e+00 -4.26642159e-17]
 [-4.26642159e-17  1.00000000e+00]]


2. Apply Gram–Schmidt on the vectors $(1,1,0)$ and $(1,0,1)$, and compute the resulting orthonormal basis.  

In [ ]:
u1 = np.array([1, 1, 0])
array([[1.00000000e+00, 1.03018891e-16],
       [1.03018891e-16, 1.00000000e+00]])
u2 = np.array([1, 0, 1])

v1 = u1 / np.linalg.norm(u1)
print(v1)
v2 = u2 - np.dot(u2, v1) * v1
v2 = v2 / np.linalg.norm(v2)
print(v2)

Q = np.column_stack((v1, v2))
Q.T @ Q  # should be identity matrix

[0.70710678 0.70710678 0.        ]
[ 0.40824829 -0.40824829  0.81649658]


array([[1.00000000e+00, 1.03018891e-16],
       [1.03018891e-16, 1.00000000e+00]])

3. In Python, generate a random $3 \times 3$ matrix and orthonormalize its columns. 

In [25]:
def generate_orthogonal_matrix_using_gram_schmidt(A):
    Q = np.zeros_like(A)
    for i in range(A.shape[1]):
        u = A[:, i]
        for j in range(i):
            u -= np.dot(u, Q[:, j]) * Q[:, j]
        Q[:, i] = u / np.linalg.norm(u)
    return Q
random_matrix = np.random.rand(3, 3)
print("Random 3x3 matrix:", random_matrix, sep="\n")
Q = generate_orthogonal_matrix_using_gram_schmidt(random_matrix)
print("Orthogonal matrix Q from Gram-Schmidt:", Q, sep="\n")
print("Q^T @ Q (should be identity):", (Q.T @ Q).astype(int), sep="\n")

Random 3x3 matrix:
[[0.28322376 0.26380351 0.73747741]
 [0.62294003 0.40961804 0.80281759]
 [0.44313677 0.01150417 0.7224955 ]]
Orthogonal matrix Q from Gram-Schmidt:
[[ 0.34740526  0.4619311   0.81604488]
 [ 0.76410483  0.36499638 -0.53190361]
 [ 0.54355625 -0.80832995  0.22616212]]
Q^T @ Q (should be identity):
[[1 0 0]
 [0 0 0]
 [0 0 1]]


1. Compute the eigenvalues and eigenvectors of  

   $$
   \begin{bmatrix}
   4 & 2 \\
   1 & 3
   \end{bmatrix}
   $$  

In [26]:
A = np.array([[4, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Matrix A:", A, sep="\n")
print("Eigenvalues:", eigenvalues, sep="\n")
print("Eigenvectors:", eigenvectors, sep="\n")

Matrix A:
[[4 2]
 [1 3]]
Eigenvalues:
[5. 2.]
Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



2. Verify in Python that $A v = \lambda v$ for one eigenpair.  



In [ ]:
# verify A v = λ v for one eigenpair
lambda_1 = eigenvalues[0]
v1 = eigenvectors[:, 0]

print("Verifying A v = λ v for the first eigenpair:")
print("A v1:", A @ v1, sep="\n")
print("λ1 v1:", lambda_1 * v1, sep="\n")
print("A v1 == λ1 v1 ?", np.allclose(A @ v1, lambda_1 * v1)), lambda_1 * v1))

3. Generate a random $3 \times 3$ matrix in Python and compute its eigenvalues and eigenvectors using `np.linalg.eig`.  