# Session 2 — Rough Notebook
Run the code hints from the Session 2 READMEs. This is a free-form execution notebook. You can change, re-run, and experiment.

---

## Imports and helper functions

In [8]:
import numpy as np
from numpy.linalg import eig, det, inv, matrix_rank

def gram_schmidt_cols(A):
    A = A.astype(float)
    m, n = A.shape
    Q = np.zeros((m, n))
    for j in range(n):
        v = A[:, j].copy()
        for i in range(j):
            proj = np.dot(Q[:, i], A[:, j]) * Q[:, i]
            v = v - proj
        norm = np.linalg.norm(v)
        if norm < 1e-12:
            Q[:, j] = v
        else:
            Q[:, j] = v / norm
    return Q

print('Helper functions loaded.')

Helper functions loaded.


## Matrix transpose, determinant, inverse

In [9]:
# Example matrix
A = np.random.rand(4,4)
print('A:\n', A)
print('\nA.T:\n', A.T)
print('\ndet(A)=', det(A))
# inverse only if det != 0
if abs(det(A)) > 1e-12:
    print('\ninv(A) computed')
    print(inv(A))
else:
    print('\nMatrix singular; no inverse')

A:
 [[0.26370554 0.93662976 0.16443281 0.50380497]
 [0.84057924 0.6353519  0.80252722 0.25074555]
 [0.39729195 0.39989034 0.2698241  0.96309501]
 [0.12273327 0.33088483 0.36113526 0.33095108]]

A.T:
 [[0.26370554 0.84057924 0.39729195 0.12273327]
 [0.93662976 0.6353519  0.39989034 0.33088483]
 [0.16443281 0.80252722 0.2698241  0.36113526]
 [0.50380497 0.25074555 0.96309501 0.33095108]]

det(A)= 0.14228246571550293

inv(A) computed
[[-0.00622156  1.29117716  0.87736383 -3.52199248]
 [ 1.40764335 -0.10369656 -0.76460672  0.16078706]
 [-1.01492775  0.14107466 -0.68404051  3.42874791]
 [-0.29756071 -0.52909876  1.18551114  0.42550657]]


## Solve linear system

In [10]:
# Solve a sample linear system
A = np.array([[1,1,1],[0,2,5],[2,5,-1]], dtype=float)
b = np.array([6,-4,27], dtype=float)
print('Solve A x = b ->', np.linalg.solve(A,b))

Solve A x = b -> [ 5.  3. -2.]


## Orthogonality check and QR to get orthogonal matrix

In [11]:
# Orthogonality check for random matrix
A = np.random.rand(3,3)
print('A^T A:\n', A.T @ A)
print('Is orthogonal?', np.allclose(A.T @ A, np.eye(3)))

# QR decomposition to obtain orthogonal Q
Q, R = np.linalg.qr(np.random.rand(3,3))
print('\nQ from QR:\n', Q)
print('\nQ^T Q:\n', np.round(Q.T @ Q,6))

A^T A:
 [[0.74505171 0.90780714 0.67045062]
 [0.90780714 1.17324934 0.83796528]
 [0.67045062 0.83796528 0.65887845]]
Is orthogonal? False

Q from QR:
 [[-0.2072843   0.97826343  0.00582051]
 [-0.77398285 -0.16035461 -0.61256587]
 [-0.59831745 -0.13148026  0.79039811]]

Q^T Q:
 [[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


## Gram-Schmidt example

In [12]:
G = np.array([[2.0,2.0,4.0],[0.0,3.0,5.0],[0.0,4.0,5.0]])
Q = gram_schmidt_cols(G)
print('Q:\n', Q)
print('\nQ^T Q:\n', np.round(Q.T @ Q,6))

Q:
 [[ 1.   0.   0. ]
 [ 0.   0.6  0.8]
 [ 0.   0.8 -0.6]]

Q^T Q:
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


## Eigen decomposition and diagonalization

In [13]:
A = np.array([[2,1],[1,1]], dtype=float)
vals, vecs = eig(A)
print('eigvals:', vals)
print('eigvecs:\n', vecs)
# Diagonalize and compute power
D = np.diag(vals)
A_recon = vecs @ D @ np.linalg.inv(vecs)
print('\nA reconstructed:\n', np.round(A_recon,6))

eigvals: [2.61803399 0.38196601]
eigvecs:
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]

A reconstructed:
 [[2. 1.]
 [1. 1.]]


## Rotation matrix example

In [14]:
theta = np.pi/2
R = np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta), np.cos(theta)]])
print('R:\n', R)
print('\nRounded R:\n', np.round(R,6))

R:
 [[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]

Rounded R:
 [[ 0. -1.]
 [ 1.  0.]]
