# Session 2 — Rough Notebook
Run the code hints from the Session 2 READMEs. This is a free-form execution notebook. You can change, re-run, and experiment.

---

## Imports and helper functions

In [1]:
import numpy as np
from numpy.linalg import eig, det, inv, matrix_rank

def gram_schmidt_cols(A):
    A = A.astype(float)
    m, n = A.shape
    Q = np.zeros((m, n))
    for j in range(n):
        v = A[:, j].copy()
        for i in range(j):
            proj = np.dot(Q[:, i], A[:, j]) * Q[:, i]
            v = v - proj
        norm = np.linalg.norm(v)
        if norm < 1e-12:
            Q[:, j] = v
        else:
            Q[:, j] = v / norm
    return Q

print('Helper functions loaded.')

Helper functions loaded.


## Matrix transpose, determinant, inverse

In [2]:
# Example matrix
A = np.random.rand(4,4)
print('A:\n', A)
print('\nA.T:\n', A.T)
print('\ndet(A)=', det(A))
# inverse only if det != 0
if abs(det(A)) > 1e-12:
    print('\ninv(A) computed')
    print(inv(A))
else:
    print('\nMatrix singular; no inverse')

A:
 [[0.03840801 0.65233987 0.97632649 0.4318799 ]
 [0.08323908 0.62945845 0.73604994 0.99714553]
 [0.57665392 0.25988573 0.57261664 0.91822607]
 [0.23143507 0.65646957 0.59251359 0.91463581]]

A.T:
 [[0.03840801 0.08323908 0.57665392 0.23143507]
 [0.65233987 0.62945845 0.25988573 0.65646957]
 [0.97632649 0.73604994 0.57261664 0.59251359]
 [0.4318799  0.99714553 0.91822607 0.91463581]]

det(A)= 0.06799200666296241

inv(A) computed
[[ 0.50949679 -3.63780847  1.22288254  2.4977159 ]
 [ 0.36670525 -3.2050184  -1.49834396  4.82521631]
 [ 1.30724971  1.20516723  0.86088235 -2.79541494]
 [-1.23897344  2.44013574  0.20829582 -1.19101544]]


## Solve linear system

In [3]:
# Solve a sample linear system
A = np.array([[1,1,1],[0,2,5],[2,5,-1]], dtype=float)
b = np.array([6,-4,27], dtype=float)
print('Solve A x = b ->', np.linalg.solve(A,b))

Solve A x = b -> [ 5.  3. -2.]


## Orthogonality check and QR to get orthogonal matrix

In [4]:
# Orthogonality check for random matrix
A = np.random.rand(3,3)
print('A^T A:\n', A.T @ A)
print('Is orthogonal?', np.allclose(A.T @ A, np.eye(3)))

# QR decomposition to obtain orthogonal Q
Q, R = np.linalg.qr(np.random.rand(3,3))
print('\nQ from QR:\n', Q)
print('\nQ^T Q:\n', np.round(Q.T @ Q,6))

A^T A:
 [[0.916393   0.80822678 0.84339984]
 [0.80822678 1.31131647 0.88329052]
 [0.84339984 0.88329052 0.91452328]]
Is orthogonal? False

Q from QR:
 [[-0.64430477  0.36276989 -0.67325282]
 [-0.74406431 -0.5008095   0.44221957]
 [-0.17674746  0.78586758  0.59259808]]

Q^T Q:
 [[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


## Gram-Schmidt example

In [5]:
G = np.array([[2.0,2.0,4.0],[0.0,3.0,5.0],[0.0,4.0,5.0]])
Q = gram_schmidt_cols(G)
print('Q:\n', Q)
print('\nQ^T Q:\n', np.round(Q.T @ Q,6))

Q:
 [[ 1.   0.   0. ]
 [ 0.   0.6  0.8]
 [ 0.   0.8 -0.6]]

Q^T Q:
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


## Eigen decomposition and diagonalization

In [6]:
A = np.array([[2,1],[1,1]], dtype=float)
vals, vecs = eig(A)
print('eigvals:', vals)
print('eigvecs:\n', vecs)
# Diagonalize and compute power
D = np.diag(vals)
A_recon = vecs @ D @ np.linalg.inv(vecs)
print('\nA reconstructed:\n', np.round(A_recon,6))

eigvals: [2.61803399 0.38196601]
eigvecs:
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]

A reconstructed:
 [[2. 1.]
 [1. 1.]]


## Rotation matrix example

In [7]:
theta = np.pi/2
R = np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta), np.cos(theta)]])
print('R:\n', R)
print('\nRounded R:\n', np.round(R,6))

R:
 [[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]

Rounded R:
 [[ 0. -1.]
 [ 1.  0.]]
