In [1]:
import numpy as np

# Example vector
v = np.array([2, 3])

# Scaling
S = np.array([[2, 0],
              [0, 1.5]])
print("Scaling:", S @ v)

# Reflection about x-axis
Rx = np.array([[1, 0],
               [0, -1]])
print("Reflection (x-axis):", Rx @ v)

# Projection onto x-axis
P = np.array([[1, 0],
              [0, 0]])
print("Projection:", P @ v)

# Rotation 45 degrees
theta = np.pi / 4
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])
print("Rotation 45°:", R @ v)

Scaling: [4.  4.5]
Reflection (x-axis): [ 2 -3]
Projection: [2 0]
Rotation 45°: [-0.70710678  3.53553391]


In [2]:
# 2x2 matrix
A = np.array([[2, 3],
              [1, 4]])
print("Determinant (2x2):", np.linalg.det(A))

# 3x3 matrix
B = np.array([[2, 3, 4],
              [3, 4, 5],
              [5, 6, 3]])
print("Determinant (3x3):", np.linalg.det(B))

Determinant (2x2): 5.000000000000001
Determinant (3x3): 4.000000000000003


In [3]:
# Example matrix
A = np.array([[2, 1],
              [7, 4]])

# Inverse
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)

# Verify A * A^-1 = I
I = A @ inv_A
print("Verification (A * A^-1):\n", I)

Inverse of A:
 [[ 4. -1.]
 [-7.  2.]]
Verification (A * A^-1):
 [[1. 0.]
 [0. 1.]]


In [4]:
# Diagonal matrix
D = np.diag([2, 5, 10])
print("Determinant (Diagonal):", np.linalg.det(D))
print("Inverse (Diagonal):\n", np.linalg.inv(D), end="\n\n")

# Orthogonal matrix example (rotation 90°)
Q = np.array([[0, -1],
              [1,  0]])
print("Determinant (Orthogonal):", np.linalg.det(Q))
print("Q^T == Q^-1 ?", np.allclose(Q.T, np.linalg.inv(Q)), end="\n\n")

# Upper triangular matrix
U = np.array([[2, 3, 1],
              [0, 5, 4],
              [0, 0, 6]])
print("Determinant (Upper Triangular):", np.linalg.det(U))

Determinant (Diagonal): 100.00000000000004
Inverse (Diagonal):
 [[0.5 0.  0. ]
 [0.  0.2 0. ]
 [0.  0.  0.1]]

Determinant (Orthogonal): 1.0
Q^T == Q^-1 ? True

Determinant (Upper Triangular): 59.999999999999986


In [21]:
def gram_schmidt(A):
    """Orthonormalize the columns of matrix A using Gram-Schmidt."""
    # here setting dtype to float to avoid integer division issues
    Q = np.zeros_like(A, dtype=float)
    # here we iterate over columns of A
    for i in range(A.shape[1]):
        #  here we convert to float to avoid integer division issues
        v = A[:, i].astype(float)
        # here we iterate over previous columns
        for j in range(i):
            # here we project v onto Q[:, j] and subtract it from v
            v -= np.dot(Q[:, j], A[:, i]) * Q[:, j]
        # here we normalize v to get the orthonormal vector
        Q[:, i] = v / np.linalg.norm(v)
    return Q

# Example
A = np.array([[2, 2, 4],
              [0, 3, 5],
              [0, 4, 5]])
Q = gram_schmidt(A)
print("Orthonormal basis:\n", Q)
print("Check Q^T Q = I:\n", Q.T @ Q)

Orthonormal basis:
 [[ 1.   0.   0. ]
 [ 0.   0.6  0.8]
 [ 0.   0.8 -0.6]]
Check Q^T Q = I:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -6.03961325e-16]
 [ 0.00000000e+00 -6.03961325e-16  1.00000000e+00]]


In [22]:
A = np.array([[2, 1],
              [1, 1]])

# Eigenvalues and Eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues: [2.61803399 0.38196601]
Eigenvectors:
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
